- project:
    templates:
      - openstack-python-jobs-neutron
      - publish-openstack-sphinx-docs
      - release-notes-jobs
      - check-requirements
      - openstack-python35-jobs-neutron
    check:
      jobs:
        - openstack-tox-cover:
            required-projects:
              - openstack/neutron
            voting: false
