- project:
    templates:
      - openstack-python-jobs-neutron
      - publish-openstack-docs-pti
      - release-notes-jobs-python3
      - check-requirements
      - openstack-python35-jobs-neutron
      - openstack-python36-jobs-neutron
      - openstack-lower-constraints-jobs-neutron
    check:
      jobs:
        - networking-ovn-tempest-dsvm-ovs-master:
            voting: false
        - networking-ovn-tempest-dsvm-ovs-release
        - networking-ovn-tempest-dsvm-ovs-release-python2
        - networking-ovn-rally-task
        - networking-ovn-dsvm-functional
        - networking-ovn-dsvm-functional-py35:
            branches: ^(?!stable/newton).*$
        # TripleO jobs that deploy OVN.
        # Note we don't use a project-template here, so it's easier
        # to disable voting on one specific job if things go wrong.
        # tripleo-ci-centos-7-scenario007-multinode-oooq-container will
        # run in Pike and beyond.
        # If you need any support to debug these jobs in case of
        # failures, please reach us on #tripleo IRC channel.
        - networking-ovn-tripleo-c7-s007-oooq-containers
        - networking-ovn-dsvm-grenade:
            branches: ^(?!stable/(ocata|pike|queens)).*$
            voting: false
        - openstack-tox-cover:
            required-projects:
              - openstack/neutron
            voting: false
    gate:
      jobs:
        - networking-ovn-tempest-dsvm-ovs-release
        - networking-ovn-tempest-dsvm-ovs-release-python2
        - networking-ovn-rally-task
        - networking-ovn-dsvm-functional
        - networking-ovn-dsvm-functional-py35:
            branches: ^(?!stable/newton).*$
        - tripleo-ci-centos-7-scenario007-multinode-oooq
        - tripleo-ci-centos-7-scenario007-multinode-oooq-container
    experimental:
      jobs:
        - networking-ovn-tempest-dsvm-multinode:
            voting: false
            branches: ^(?!stable/newton).*$
        - kuryr-kubernetes-tempest-ovn
    periodic:
      jobs:
        - openstack-tox-py35-with-ovsdbapp-master:
            required-projects:
              - openstack/neutron
        - networking-ovn-tempest-dsvm-ovs-master-fedora

